name: algae
channels:
  - defaults
dependencies:
  - blas
  - brotli
  - ca-certificates
  - certifi
  - cycler
  - fonttools
  - freetype
  - icc_rt
  - icu
  - intel-openmp
  - jpeg
  - kiwisolver
  - libpng
  - libtiff
  - libwebp
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - numpy
  - numpy-base
  - olefile
  - openssl
  - packaging
  - pillow
  - pip
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - qt
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - tzdata
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - xz
  - zlib
  - zstd
